/**
 * Build capsize CSS classes for every DASH type-scale step.
 * Output: build/metrics.css with utility classes like:
 *
 *   .capsize-display { font-size: 46px; line-height: 48px; padding: ...; }
 *   .capsize-display::before / ::after — trim half-leading
 *
 * Consumers can `@import "@dash/metrics/css"` and apply the class,
 * getting cap-line snapping for free.
 */

import { createStyleString } from '@capsizecss/core';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { geistMetrics, geistMonoMetrics } from './metrics-data.js';

// These must stay in sync with @dash/tokens font.size and font.lineHeight.
// TODO: import from @dash/tokens once the workspace symlink is verified.
const STEPS = [
  { key: 'display', font: geistMetrics, fontSize: 46, leading: 48 },
  { key: 'deck',    font: geistMetrics, fontSize: 22, leading: 32 },
  { key: 'body',    font: geistMetrics, fontSize: 14, leading: 24 },
  { key: 'meta',    font: geistMetrics, fontSize: 11, leading: 16 },
  { key: 'micro',   font: geistMetrics, fontSize: 10, leading: 16 }, // 9.5 rounded to integer
  { key: 'mono-body',  font: geistMonoMetrics, fontSize: 14, leading: 24 },
  { key: 'mono-meta',  font: geistMonoMetrics, fontSize: 11, leading: 16 },
  { key: 'mono-micro', font: geistMonoMetrics, fontSize: 10, leading: 16 },
] as const;

function build() {
  const header = `/* Generated by @dash/metrics — DO NOT EDIT BY HAND.
 * Regenerate: bun --filter=@dash/metrics build
 * Cap-line snapping via capsize. All leading values multiples of 8.
 */\n\n`;

  const body = STEPS.map((step) => {
    return createStyleString(`capsize-${step.key}`, {
      fontMetrics: step.font,
      fontSize: step.fontSize,
      leading: step.leading,
    });
  }).join('\n\n');

  const outPath = resolve(import.meta.dir, '../build/metrics.css');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, header + body, 'utf-8');

  console.log(`✓ Wrote ${STEPS.length} capsize classes → build/metrics.css`);
}

if (import.meta.main) {
  build();
}
